# Generated by Django 3.1.4 on 2020-12-08 10:17

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_sitelist_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelist',
            name='result',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
